# Generated by Django 5.2.6 on 2025-12-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.CharField(db_column='음식ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='음식명', max_length=50)),
                ('category', models.CharField(db_column='분류', max_length=20)),
                ('price', models.IntegerField(db_column='가격')),
            ],
            options={
                'db_table': '식음료',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(db_column='회원ID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='이름', max_length=50)),
                ('age', models.IntegerField(db_column='나이')),
                ('phone', models.CharField(db_column='전화번호', max_length=20)),
                ('grade', models.CharField(db_column='등급', default='일반', max_length=10)),
            ],
            options={
                'db_table': '회원',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(db_column='영화ID', max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='제목', max_length=100)),
                ('genre', models.CharField(blank=True, db_column='장르', max_length=30, null=True)),
                ('running_time', models.IntegerField(blank=True, db_column='상영시간', null=True)),
                ('rating', models.CharField(blank=True, db_column='관람등급', max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, db_column='가격', null=True)),
                ('poster', models.CharField(blank=True, db_column='poster', max_length=300, null=True)),
            ],
            options={
                'db_table': '영화',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater_id', models.CharField(db_column='상영관ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='관이름', max_length=20)),
                ('seats', models.IntegerField(db_column='좌석수')),
            ],
            options={
                'db_table': '상영관',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(db_column='주문ID', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='주문날짜')),
                ('total_price', models.IntegerField(db_column='총금액')),
                ('member', models.ForeignKey(db_column='회원ID', on_delete=django.db.models.deletion.CASCADE, to='cinema.member')),
            ],
            options={
                'db_table': '주문',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detail_id', models.CharField(db_column='주문상세ID', max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='수량')),
                ('food', models.ForeignKey(db_column='음식ID', on_delete=django.db.models.deletion.CASCADE, to='cinema.food')),
                ('order', models.ForeignKey(db_column='주문ID', on_delete=django.db.models.deletion.CASCADE, to='cinema.order')),
            ],
            options={
                'db_table': '주문상세',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(db_column='상영ID', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='상영날짜')),
                ('time', models.TimeField(db_column='상영시간')),
                ('movie', models.ForeignKey(db_column='영화ID', on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
                ('theater', models.ForeignKey(db_column='상영관ID', on_delete=django.db.models.deletion.CASCADE, to='cinema.theater')),
            ],
            options={
                'db_table': '상영정보',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.CharField(db_column='예매ID', max_length=10, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(db_column='좌석번호', max_length=5)),
                ('reserved_at', models.DateField(db_column='예매일자')),
                ('member', models.ForeignKey(db_column='회원ID', on_delete=django.db.models.deletion.CASCADE, to='cinema.member')),
                ('schedule', models.ForeignKey(db_column='상영ID', on_delete=django.db.models.deletion.CASCADE, to='cinema.schedule')),
            ],
            options={
                'db_table': '예매',
            },
        ),
    ]
