# Generated by Django 5.2.6 on 2025-12-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, db_column='비밀번호', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_column='주문ID', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='detail_id',
            field=models.CharField(db_column='주문상세ID', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(db_column='예매ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
