# Generated by Django 5.2.6 on 2025-12-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(db_column='예매ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
