# Generated by Django 5.2.6 on 2025-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_reservation_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_column='주문ID', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='detail_id',
            field=models.CharField(db_column='주문상세ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
