# Generated by Django 5.2.6 on 2025-12-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_order_order_id_alter_orderdetail_detail_id'),
    ]

    operations = [
    ]
